# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Paulo Romano"

author:
  twitter:          paulo_romano
  github:           paulo-romano
  stackoverflow:    7089306
  quora:            Paulo-Romano
  linkedin:         paulo-romano
  reddit:           Promano
  medium:           paulo_romano
  email:            contato@pauloromano.tech

copyright:
  year:             2018
  name:             Paulo Romano

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "pauloromano"

# URL
url:                "https://pauloromano.tech" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Sao_Paulo
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]